[package]
name = "snake_cli_bouncer"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
term_size = "0.3.2"
ansi_term = "0.12.1"
colored = "2.1.0"
clap = { version = "4.4.18", features = ["derive"] }
